theme: jekyll-theme-minimal
title: Otniel Tamini - Portfolio DevOps & Cloud
description: Portfolio professionnel d'Otniel Tamini, Ingénieur DevOps et Cloud Computing
show_downloads: false
google_analytics: # À configurer si nécessaire
